// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stock.proto

package stock;

public interface currencyDataOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required .stock.currency curr = 1;
  /**
   * <code>required .stock.currency curr = 1;</code>
   */
  boolean hasCurr();
  /**
   * <code>required .stock.currency curr = 1;</code>
   */
  stock.currency getCurr();

  // required double value = 2;
  /**
   * <code>required double value = 2;</code>
   */
  boolean hasValue();
  /**
   * <code>required double value = 2;</code>
   */
  double getValue();
}
