// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stock.proto

package stock;

/**
 * Protobuf type {@code stock.stockRequest}
 */
public  final class stockRequest extends
    com.google.protobuf.GeneratedMessage
    implements stockRequestOrBuilder {
  // Use stockRequest.newBuilder() to construct.
  private stockRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private stockRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final stockRequest defaultInstance;
  public static stockRequest getDefaultInstance() {
    return defaultInstance;
  }

  public stockRequest getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private stockRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              currencies_ = new java.util.ArrayList<stock.currencyData>();
              mutable_bitField0_ |= 0x00000001;
            }
            currencies_.add(input.readMessage(stock.currencyData.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        currencies_ = java.util.Collections.unmodifiableList(currencies_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return stock.Stock.internal_static_stock_stockRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return stock.Stock.internal_static_stock_stockRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            stock.stockRequest.class, stock.stockRequest.Builder.class);
  }

  public static com.google.protobuf.Parser<stockRequest> PARSER =
      new com.google.protobuf.AbstractParser<stockRequest>() {
    public stockRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new stockRequest(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<stockRequest> getParserForType() {
    return PARSER;
  }

  // repeated .stock.currencyData currencies = 1;
  public static final int CURRENCIES_FIELD_NUMBER = 1;
  private java.util.List<stock.currencyData> currencies_;
  /**
   * <code>repeated .stock.currencyData currencies = 1;</code>
   */
  public java.util.List<stock.currencyData> getCurrenciesList() {
    return currencies_;
  }
  /**
   * <code>repeated .stock.currencyData currencies = 1;</code>
   */
  public java.util.List<? extends stock.currencyDataOrBuilder> 
      getCurrenciesOrBuilderList() {
    return currencies_;
  }
  /**
   * <code>repeated .stock.currencyData currencies = 1;</code>
   */
  public int getCurrenciesCount() {
    return currencies_.size();
  }
  /**
   * <code>repeated .stock.currencyData currencies = 1;</code>
   */
  public stock.currencyData getCurrencies(int index) {
    return currencies_.get(index);
  }
  /**
   * <code>repeated .stock.currencyData currencies = 1;</code>
   */
  public stock.currencyDataOrBuilder getCurrenciesOrBuilder(
      int index) {
    return currencies_.get(index);
  }

  private void initFields() {
    currencies_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    for (int i = 0; i < getCurrenciesCount(); i++) {
      if (!getCurrencies(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    for (int i = 0; i < currencies_.size(); i++) {
      output.writeMessage(1, currencies_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < currencies_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, currencies_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static stock.stockRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stock.stockRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stock.stockRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stock.stockRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stock.stockRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static stock.stockRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static stock.stockRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static stock.stockRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static stock.stockRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static stock.stockRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(stock.stockRequest prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code stock.stockRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements stock.stockRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return stock.Stock.internal_static_stock_stockRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return stock.Stock.internal_static_stock_stockRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              stock.stockRequest.class, stock.stockRequest.Builder.class);
    }

    // Construct using stock.stockRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getCurrenciesFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      if (currenciesBuilder_ == null) {
        currencies_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        currenciesBuilder_.clear();
      }
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return stock.Stock.internal_static_stock_stockRequest_descriptor;
    }

    public stock.stockRequest getDefaultInstanceForType() {
      return stock.stockRequest.getDefaultInstance();
    }

    public stock.stockRequest build() {
      stock.stockRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public stock.stockRequest buildPartial() {
      stock.stockRequest result = new stock.stockRequest(this);
      int from_bitField0_ = bitField0_;
      if (currenciesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          currencies_ = java.util.Collections.unmodifiableList(currencies_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.currencies_ = currencies_;
      } else {
        result.currencies_ = currenciesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof stock.stockRequest) {
        return mergeFrom((stock.stockRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(stock.stockRequest other) {
      if (other == stock.stockRequest.getDefaultInstance()) return this;
      if (currenciesBuilder_ == null) {
        if (!other.currencies_.isEmpty()) {
          if (currencies_.isEmpty()) {
            currencies_ = other.currencies_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCurrenciesIsMutable();
            currencies_.addAll(other.currencies_);
          }
          onChanged();
        }
      } else {
        if (!other.currencies_.isEmpty()) {
          if (currenciesBuilder_.isEmpty()) {
            currenciesBuilder_.dispose();
            currenciesBuilder_ = null;
            currencies_ = other.currencies_;
            bitField0_ = (bitField0_ & ~0x00000001);
            currenciesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getCurrenciesFieldBuilder() : null;
          } else {
            currenciesBuilder_.addAllMessages(other.currencies_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      for (int i = 0; i < getCurrenciesCount(); i++) {
        if (!getCurrencies(i).isInitialized()) {
          
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      stock.stockRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (stock.stockRequest) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // repeated .stock.currencyData currencies = 1;
    private java.util.List<stock.currencyData> currencies_ =
      java.util.Collections.emptyList();
    private void ensureCurrenciesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        currencies_ = new java.util.ArrayList<stock.currencyData>(currencies_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        stock.currencyData, stock.currencyData.Builder, stock.currencyDataOrBuilder> currenciesBuilder_;

    /**
     * <code>repeated .stock.currencyData currencies = 1;</code>
     */
    public java.util.List<stock.currencyData> getCurrenciesList() {
      if (currenciesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(currencies_);
      } else {
        return currenciesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .stock.currencyData currencies = 1;</code>
     */
    public int getCurrenciesCount() {
      if (currenciesBuilder_ == null) {
        return currencies_.size();
      } else {
        return currenciesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .stock.currencyData currencies = 1;</code>
     */
    public stock.currencyData getCurrencies(int index) {
      if (currenciesBuilder_ == null) {
        return currencies_.get(index);
      } else {
        return currenciesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .stock.currencyData currencies = 1;</code>
     */
    public Builder setCurrencies(
        int index, stock.currencyData value) {
      if (currenciesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCurrenciesIsMutable();
        currencies_.set(index, value);
        onChanged();
      } else {
        currenciesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .stock.currencyData currencies = 1;</code>
     */
    public Builder setCurrencies(
        int index, stock.currencyData.Builder builderForValue) {
      if (currenciesBuilder_ == null) {
        ensureCurrenciesIsMutable();
        currencies_.set(index, builderForValue.build());
        onChanged();
      } else {
        currenciesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .stock.currencyData currencies = 1;</code>
     */
    public Builder addCurrencies(stock.currencyData value) {
      if (currenciesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCurrenciesIsMutable();
        currencies_.add(value);
        onChanged();
      } else {
        currenciesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .stock.currencyData currencies = 1;</code>
     */
    public Builder addCurrencies(
        int index, stock.currencyData value) {
      if (currenciesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCurrenciesIsMutable();
        currencies_.add(index, value);
        onChanged();
      } else {
        currenciesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .stock.currencyData currencies = 1;</code>
     */
    public Builder addCurrencies(
        stock.currencyData.Builder builderForValue) {
      if (currenciesBuilder_ == null) {
        ensureCurrenciesIsMutable();
        currencies_.add(builderForValue.build());
        onChanged();
      } else {
        currenciesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .stock.currencyData currencies = 1;</code>
     */
    public Builder addCurrencies(
        int index, stock.currencyData.Builder builderForValue) {
      if (currenciesBuilder_ == null) {
        ensureCurrenciesIsMutable();
        currencies_.add(index, builderForValue.build());
        onChanged();
      } else {
        currenciesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .stock.currencyData currencies = 1;</code>
     */
    public Builder addAllCurrencies(
        java.lang.Iterable<? extends stock.currencyData> values) {
      if (currenciesBuilder_ == null) {
        ensureCurrenciesIsMutable();
        super.addAll(values, currencies_);
        onChanged();
      } else {
        currenciesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .stock.currencyData currencies = 1;</code>
     */
    public Builder clearCurrencies() {
      if (currenciesBuilder_ == null) {
        currencies_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        currenciesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .stock.currencyData currencies = 1;</code>
     */
    public Builder removeCurrencies(int index) {
      if (currenciesBuilder_ == null) {
        ensureCurrenciesIsMutable();
        currencies_.remove(index);
        onChanged();
      } else {
        currenciesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .stock.currencyData currencies = 1;</code>
     */
    public stock.currencyData.Builder getCurrenciesBuilder(
        int index) {
      return getCurrenciesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .stock.currencyData currencies = 1;</code>
     */
    public stock.currencyDataOrBuilder getCurrenciesOrBuilder(
        int index) {
      if (currenciesBuilder_ == null) {
        return currencies_.get(index);  } else {
        return currenciesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .stock.currencyData currencies = 1;</code>
     */
    public java.util.List<? extends stock.currencyDataOrBuilder> 
         getCurrenciesOrBuilderList() {
      if (currenciesBuilder_ != null) {
        return currenciesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(currencies_);
      }
    }
    /**
     * <code>repeated .stock.currencyData currencies = 1;</code>
     */
    public stock.currencyData.Builder addCurrenciesBuilder() {
      return getCurrenciesFieldBuilder().addBuilder(
          stock.currencyData.getDefaultInstance());
    }
    /**
     * <code>repeated .stock.currencyData currencies = 1;</code>
     */
    public stock.currencyData.Builder addCurrenciesBuilder(
        int index) {
      return getCurrenciesFieldBuilder().addBuilder(
          index, stock.currencyData.getDefaultInstance());
    }
    /**
     * <code>repeated .stock.currencyData currencies = 1;</code>
     */
    public java.util.List<stock.currencyData.Builder> 
         getCurrenciesBuilderList() {
      return getCurrenciesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        stock.currencyData, stock.currencyData.Builder, stock.currencyDataOrBuilder> 
        getCurrenciesFieldBuilder() {
      if (currenciesBuilder_ == null) {
        currenciesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            stock.currencyData, stock.currencyData.Builder, stock.currencyDataOrBuilder>(
                currencies_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        currencies_ = null;
      }
      return currenciesBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:stock.stockRequest)
  }

  static {
    defaultInstance = new stockRequest(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:stock.stockRequest)
}

